version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python dependencies..."
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Build complete!"
  post_build:
    commands:
      - echo "Packaging application..."
      - zip -r deploy.zip * .[^.]*
artifacts:
  files:
    - deploy.zip

